### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by yangbe** [conversun/Hackintosh-MSI-Z790i-EDGE-13900K-6900XT-OpenCore#1]
1、机箱是什么型号？
2、显卡需要打驱动吗？
3、睡眠唤醒后，蓝牙wifi能正常使用吗？

**Comment by conversun** [comment]
1. 机箱是 K3PRO, SSUPD结构
2. 使用 MacPro 机型不用加WTG
3. 苹果拆机网卡比较稳定, 其他网卡唤醒可能会有问题, 如94360Z3/4

**Comment by yangbe** [comment]
我用的是拆机卡bcm943602cdp ，自从升级12以后，包括13，唤醒后都有蓝牙不自动关闭的问题，目前无解
