### ISSUE TITLE
Can you share your BIOS version and settings?

### ISSUE THREAD

**Issue by ftntming** [conversun/Hackintosh-MSI-Z790i-EDGE-13900K-6900XT-OpenCore#2]
Hello. Thanks a lot for sharing the EFI. I got the DDR4 ATX version of motherboard (MSI MPG Z790 EDGE WIFI) and same CPU (13900KF). My CPU multi score has only 19800 (compare to yours 26321). I wonder if you could share your BIOS setting so I can try to figure out the difference. Thanks a lot!

**Comment by Stick-Study** [comment]
Hi. The memory type has a **huge** impact on Geekbench 5 multi score. Usually, DDR5 memory will have a much higher score than DDR4 memory. But their Cinebench R23 scores are similar.

**Comment by ftntming** [comment]
> Hi. The memory type has a **huge** impact on Geekbench 5 multi score. Usually, DDR5 memory will have a much higher score than DDR4 memory. But their Cinebench R23 scores are similar.

Thanks Yuxuan for confirming that. I was a bit surprised to see the CPU benchmark has something to do with memory, I was assuming it's more related to the CPU L2 L3 cache size.

**Comment by conversun** [comment]
I think 19800 is abnormal, my other Z690i DDR4(4000C18) can reach 24000.
Check the following settings
```
CPU Current Limit(A): 512
Short Duration Power Limit(w): 4096
```

**Comment by ftntming** [comment]
> 

Thanks for the info. I tried them in BIOS (and used your EFI),  but still geekbench 5 multicore is 20145.
Anyway I'll keep trying when I'm free. Maybe it's because my CPU had high temperature so it throttled during testing.

My cpu has lower scores in the following testing aspects, 
<img width="788" alt="low-score-aspects" src="https://user-images.githubusercontent.com/59328694/216116493-2d68d50b-1733-4340-b74c-b27bbb847739.png">

**Comment by Stick-Study** [comment]
Hi, can you try to run Cinebench R23 Muilt Core test? I asked my friend about his hackintosh and he got 40382. 
The configuration of his computer is 13900K + DDR5 6400 MHz

**Comment by ftntming** [comment]
> Hi, can you try to run Cinebench R23 Muilt Core test? I asked my friend about his hackintosh and he got 40382. The configuration of his computer is 13900K + DDR5 6400 MHz

Hi Yuxuan, my buid scored 36848 in Cinebench R23.

<img width="413" alt="my_13900KF_cinebench_r23" src="https://user-images.githubusercontent.com/59328694/216729270-c048148e-81b2-41d9-9f62-f7d05f8bdbf0.png">

**Comment by conversun** [comment]
This is my previous score, unlock power and good cooling
![dgpucJ](https://img.trackcloud.top/uPic/dgpucJ.png)

**Comment by ednitworld** [comment]
i am using gigabyte z790 UD Motherboard with i9 13900k processor, i'm installing first time hackintosh on this pc, when i click on usb on boot menu it get a black screen and get back to boot menu, please get me some solution.

**Comment by ednitworld** [comment]
https://user-images.githubusercontent.com/127900160/225148699-6c5cce6f-bcb0-405d-981c-df552bcacced.mp4


i am using gigabyte z790 UD Motherboard with i9 13900k processor, i'm installing first time hackintosh on this pc, when i click on usb on boot menu it get a black screen and get back to boot menu, please get me some solution.

**Comment by ftntming** [comment]
Hi everyone, I'm pretty sure it's the DDR5 memory that make difference. I have a new build with DDR5 5600MHz and the score is 2242 (single), 26126(multi) with default BIOS.
<img width="553" alt="DDR5-Memory" src="https://user-images.githubusercontent.com/59328694/225710553-0e3aa549-c6b5-4727-a624-3b2b892bd812.png">

**Comment by ftntming** [comment]
> i am using gigabyte z790 UD Motherboard with i9 13900k processor, i'm installing first time hackintosh on this pc, when i click on usb on boot menu it get a black screen and get back to boot menu, please get me some solution.

Hello, in your case, it could be BIOS setting or KEXT issue or others. Hackintosh is a complicated and tiresome prodcess so you have to try and fail many times. You can start with similar successful builds and their EFI and make reasonable changes to optimize it for your own build. You can check https://www.tonymacx86.com/forums/user-builds.28 for successful user builds.
