### ISSUE TITLE
Can the system start without discrete  grapics?

### ISSUE THREAD

**Issue by ChanaLii** [conversun/Hackintosh-MSI-Z790i-EDGE-13900K-6900XT-OpenCore#3]
If there is only a 13900k cpu without a drive-free discrete graphics card, can the system start?sure, I have a RTX3070 grapics but it not support drive-free.

**Comment by conversun** [comment]
> If there is only a 13900k cpu without a drive-free discrete graphics card, can the system start?sure, I have a RTX3070 grapics but it not support drive-free.

It will start and go to the desktop, but it will be very, very laggy, which is pointless

It is recommended that you replace the 6800XT/6900XT😁
