### ISSUE TITLE
Usb 3 speed

### ISSUE THREAD

**Issue by nightshadecf** [conversun/Hackintosh-MSI-Z790i-EDGE-13900K-6900XT-OpenCore#4]
I'm having this board and all usb 3.2 gen 1 works fine ( blue ports 5gbps speed)
However all the red ports (gen2) and usb C port are slow. Red ports showing only 480 mbps and type C showing only 5gbps.
Any idea how to solve this?
Thanks

**Comment by conversun** [comment]
Already supports all ports.
